### ISSUE TITLE
SSL error for untrusted/self-signed cert

### ISSUE THREAD

**Issue by organiccrap** [synacktiv/eos#1]
Hi, I'm getting SSL error on untrusted/self-signed cert.

[x] HTTPSConnectionPool(host='sub.example.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

**Comment by aevy-syn** [comment]
Hi, thanks for using the tool!
We just added a `-k` cli switch to ignore SSL cert validation :)
