### ISSUE TITLE
Error: 'NoneType' object has no attribute 'find_previous'

### ISSUE THREAD

**Issue by balioune** [synacktiv/eos#10]
Hi,
I get this issue when running  eos on Symfony 2.1.13.
I think this is caused by beautifulsoup4 module, I use beautifulsoup4 version 4.10.0. Is this the correct version for eos ?
BR,

[+] Starting scan on https://URL/app_dev.php
[+] 2021-11-30 11:03:04.126848 is a great day

[+] Info
[!] Could not identify Symfony version
[!] Could not identify PHP version
[!] Could not identify Symfony environment

[+] Request logs
[+] No POST requests

[+] Phpinfo
[+] Available at https://URL/app_dev.php/_profiler/phpinfo
[+] Found 32 PHP variables
[+] Did not find any Symfony variable

[+] Project files plugin requires Symfony >= 3.0.0

[+] Routes
[x] 'NoneType' object has no attribute 'find_previous'
Traceback (most recent call last):
  File "/home/foutatoro/Desktop/Hack/env-eos/lib/python3.8/site-packages/eos/plugins/__init__.py", line 158, in run
    plugin.run()
  File "/home/foutatoro/Desktop/Hack/env-eos/lib/python3.8/site-packages/eos/plugins/routes.py", line 69, in run
    route = label.find_previous('span', class_='value').text
AttributeError: 'NoneType' object has no attribute 'find_previous'

[+] Project sources plugin requires Symfony >= 3.0.0

[+] Generated tokens: 0ab7cf
[+] Scan completed in 0:00:02

**Comment by aevy-syn** [comment]
Hi, thank you for your feedback.
Unfortunately, I have not tested EOS on very old Symfony versions. The error may come from the interface listing the application routes being different than more recent versions. I think only few code changes in the HTML parsing section below are required to adapt the tool to your Symfony version. Feel free to make a pull request if you succeed :)
(https://github.com/synacktiv/eos/blob/636394e11ebe69562d8054f4d2e81d1b03b9f0d8/eos/plugins/routes.py#L67-L68)
