### ISSUE TITLE
Be clear that this is not an issue in the source of Symfony

### ISSUE THREAD

**Issue by nicolas-grekas** [synacktiv/eos#3]
I really enjoyed https://www.synacktiv.com/posts/pentest/looting-symfony-with-eos.html and this tool looks like a cool hack.

Yet, I think the article and this repo could state clearly that the maintainers of Symfony did not do any bad job: it is stated prominently on [the doc of the profiler](https://symfony.com/doc/current/profiler.html):
> Never enable the profiler in production environments as it will lead to major security vulnerabilities in your project.

Because it doesn't highlight this, the article has been described by some as unfair or misleading towards Symfony. Clearing this up would be a welcome improvement IMHO.

Thanks for considering!

**Comment by aevy-syn** [comment]
Hi, we apologize for the misleading information. Your remark is totally fair and we updated both the blog post and the README with these clarifications.
Thanks again to all the Symfony team for their great work :)
