### ISSUE TITLE
eos does not see debug mode

### ISSUE THREAD

**Issue by foozzi** [synacktiv/eos#5]
If the site will have debug mode enabled but the panel will not display without error (404 or other), eos will exit with a message:
```
[+] Checks
[x] Target is not in debug mode!
[x] Aborted
```
can you fix this?

**Comment by aevy-syn** [comment]
Hi, this check was removed in a1e6b34bb6b278d142dadade3cb5d008667fa38b. EOS should work in your case now. Thanks for the report.
