### ISSUE TITLE
Disable the security certificate check in Python requests

### ISSUE THREAD

**Issue by bizibabe** [synacktiv/eos#8]
Hello,
Can you add the "verify=False" option in all requests to avoid crashes with request.exceptions.SSLError? pls :)

**Comment by aevy-syn** [comment]
Hello,
Is there a bug with the `-k` argument ?

**Comment by bizibabe** [comment]
Hello, 
Some options do not display with -h.
Another way to display them?

**Comment by aevy-syn** [comment]
This is due to `-k` being an option of the `scan`, `sources`, `get` and `creds` subparsers.
Any of the following commands should display the option:
```
$ eos scan -h
$ eos sources -h
$ eos get -h
$ eos creds -h
```
You can thus use `eos scan -k https://example.org`

**Comment by bizibabe** [comment]
OK great, thank you!

**Comment by aevy-syn** [comment]
You're welcome !
